<?php
/**
 * QAL Validation Manifest (Auto-Generated)
 *
 * API Version: 2025-10-20
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edit qal-validation-2025-10-20.yaml and run:
 *   php scripts/build-manifest.php validation 2025-10-20
 *
 * Generated: 2026-04-17 03:22:37
 *
 * @package qa-heatmap-analytics
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
	'id' => 'qal-validation-2025-10-20',
	'title' => 'QAL Validation Manifest (for Executor and AI)',
	'version' => '2025-10-20',
	'update' => '2026-04-17',
	'type' => 'validation_manifest',
	'description' => 'Defines strict validation rules for QAL JSON execution requests. Used for validating QAL structures before execution.',
	'structure' => array(
		'required' => array(
			'tracking_id',
			'materials',
			'time',
			'make',
			'result',
		),
	),
	'rules' => array(
		'tracking_id' => array(
			'type' => 'string',
			'description' => 'Unique identifier for the tracking site to query. Must match a tracking_id from the /guide endpoint response.',
			'pattern' => '^[a-zA-Z0-9_-]+$',
			'errors' => array(
				array(
					'code' => 'E_UNKNOWN_TRACKING_ID',
					'message' => 'Invalid tracking_id provided.',
				),
			),
		),
		'materials' => array(
			'type' => 'array',
			'description' => 'List of data sources (materials) to use in the query. Each material must have a \'name\' property.',
			'items' => array(
				'type' => 'object',
				'required' => array(
					'name',
				),
				'properties' => array(
					'name' => array(
						'type' => 'string',
						'description' => 'Material name. Allowed values: \'allpv\', \'gsc\', \'ga4_age_gender\', \'ga4_country\', \'ga4_region\', \'goal_N\', \'click_event\', \'datalayer_event\', \'page_version\', or \'events.{name}\'.',
						'pattern' => '^(allpv|gsc|ga4_age_gender|ga4_country|ga4_region|goal_[1-9]\\d*|click_event|datalayer_event|page_version|events\\.[a-zA-Z0-9_]+)$',
					),
				),
				'additionalProperties' => false,
			),
			'minItems' => 1,
			'errors' => array(
				array(
					'code' => 'E_UNKNOWN_MATERIAL',
					'message' => 'Material name not found in manifest.',
				),
			),
		),
		'time' => array(
			'type' => 'object',
			'required' => array(
				'start',
				'end',
				'tz',
			),
			'properties' => array(
				'start' => array(
					'type' => 'string',
					'format' => 'date-time',
				),
				'end' => array(
					'type' => 'string',
					'format' => 'date-time',
				),
				'tz' => array(
					'type' => 'string',
					'description' => 'IANA timezone identifier (e.g., Asia/Tokyo, UTC, America/New_York). Any valid IANA timezone is accepted.',
					'examples' => array(
						'Asia/Tokyo',
						'UTC',
						'Europe/London',
						'America/New_York',
						'America/Los_Angeles',
						'Europe/Paris',
					),
				),
			),
			'errors' => array(
				array(
					'code' => 'E_TIME_REQUIRED',
					'message' => 'Missing time.start, time.end, or time.tz.',
				),
			),
		),
		'make' => array(
			'type' => 'object',
			'description' => 'Defines views (data transformations) to create from materials. Each key is a view name, and the value defines the view\'s structure.',
			'patternProperties' => array(
				'^[a-zA-Z0-9_]+$' => array(
					'type' => 'object',
					'description' => 'View definition. Must specify \'from\' (source material) and \'keep\' (columns to select). Optionally specify \'filter\' for filtering, \'join\' for combining materials, \'add\'/\'calc\' for aggregation.',
					'required' => array(
						'from',
						'keep',
					),
					'properties' => array(
						'from' => array(
							'type' => 'array',
							'description' => 'Specify which material to use. Must contain exactly one material name.',
							'items' => array(
								'type' => 'string',
								'pattern' => '^(allpv|gsc|ga4_age_gender|ga4_country|ga4_region|goal_[1-9]\\d*|click_event|datalayer_event|page_version|events\\.[a-zA-Z0-9_]+)$',
							),
							'minItems' => 1,
							'maxItems' => 1,
						),
						'keep' => array(
							'type' => 'array',
							'description' => 'List of columns to include in the result. Must use fully qualified names in the format \'material.column_name\' (e.g., \'allpv.url\', \'gsc.keyword\'). Empty array is allowed when calc is present (aggregate-all pattern).',
							'items' => array(
								'type' => 'string',
								'pattern' => '^(allpv|gsc|ga4_age_gender|ga4_country|ga4_region|goal_[1-9]\\d*|click_event|datalayer_event|page_version|events\\.[a-zA-Z0-9_]+)\\.[a-zA-Z0-9_]+$',
							),
							'minItems' => 0,
						),
						'filter' => array(
							'type' => 'object',
							'description' => 'Filter conditions to apply. Keys are plain column names (not qualified). Values are either an array (IN clause) or an object with operator keys. Supported fields depend on material type: allpv (utm_source, utm_medium, utm_campaign, device_type, country_code, depth_position, deep_read, stop_max_sec, stop_max_pos, exit_pos, is_submit, dead_click_image_count, irritation_click_count, scroll_back_count, content_skip_count, exploration_count, prev_page_id, next_page_id, page_type, page_fetch_status, is_article, is_product, is_list, is_form, is_trust_info, is_faq, is_landing, is_search, is_account, is_cart, is_checkout, is_confirm, is_thanks, is_top_page, is_event, is_recipe, is_job, is_video, is_howto, is_qa_forum), gsc (search_type, keyword), ga4_age_gender (age, gender, sessions, active_users), ga4_country (country, sessions, active_users), ga4_region (region, sessions, active_users), goal_x (utm_source, utm_medium, utm_campaign, device_id, is_reject), click_event (is_external, action_id, page_id, to_url, selector, event_sec), page_version (page_id, device_id, version_no, update_date). Multiple conditions are implicitly AND.',
							'additionalProperties' => array(
								'oneOf' => array(
									array(
										'type' => 'array',
										'items' => array(
											'type' => array(
												'string',
												'boolean',
											),
										),
									),
									array(
										'type' => 'object',
										'propertyNames' => array(
											'enum' => array(
												'eq',
												'neq',
												'gt',
												'gte',
												'lt',
												'lte',
												'in',
												'contains',
												'prefix',
												'between',
											),
										),
									),
								),
							),
						),
						'add' => array(
							'type' => 'array',
							'description' => 'List of column names for calc results. Each element must match a key in calc.',
							'items' => array(
								'type' => 'string',
							),
						),
						'calc' => array(
							'type' => 'object',
							'description' => 'Aggregation expressions. Keys are result column names, values are expressions like \'COUNT(material.column)\'.',
							'additionalProperties' => array(
								'type' => 'string',
							),
						),
						'join' => array(
							'type' => 'object',
							'description' => 'Join another material or view. Requires \'with\' (material/view name) and \'on\' (array of {left, right} column pairs). Optional \'if not match\': \'keep-left\' (default) or \'drop\'.',
							'properties' => array(
								'with' => array(
									'type' => 'string',
									'description' => 'Name of the material or previously defined view to join with.',
								),
								'on' => array(
									'type' => 'array',
									'description' => 'Join conditions. Each element specifies a left and right column pair.',
									'items' => array(
										'type' => 'object',
										'required' => array(
											'left',
											'right',
										),
										'properties' => array(
											'left' => array(
												'type' => 'string',
												'description' => 'Qualified column from the current view\'s source.',
											),
											'right' => array(
												'type' => 'string',
												'description' => 'Qualified column from the \'with\' material/view.',
											),
										),
									),
								),
								'if not match' => array(
									'type' => 'string',
									'enum' => array(
										'keep-left',
										'drop',
									),
									'description' => 'Behavior for unmatched rows. Default: keep-left.',
								),
							),
							'required' => array(
								'with',
								'on',
							),
						),
						'sort' => array(
							'type' => 'object',
							'description' => 'Sort results and optionally limit to top N rows. Applied after calc. The \'by\' column must exist in keep or add columns. Accepts both qualified (\'material.column\') and unqualified (\'column\') names.',
							'required' => array(
								'by',
								'order',
							),
							'properties' => array(
								'by' => array(
									'type' => 'string',
									'description' => 'Column name to sort by. Can be qualified (e.g., \'click_event.click_count\') or unqualified (e.g., \'click_count\'). Must exist in keep or add columns.',
								),
								'order' => array(
									'type' => 'string',
									'enum' => array(
										'asc',
										'desc',
									),
									'description' => 'Sort order: \'asc\' for ascending, \'desc\' for descending.',
								),
								'top' => array(
									'type' => 'integer',
									'description' => 'Return only the top N rows after sorting. Omit to return all rows.',
									'minimum' => 1,
								),
							),
							'additionalProperties' => false,
						),
					),
					'additionalProperties' => false,
				),
			),
			'errors' => array(
				array(
					'code' => 'E_UNKNOWN_COLUMN',
					'message' => 'Invalid column name in keep list.',
				),
			),
		),
		'result' => array(
			'type' => 'object',
			'description' => 'Specifies which view to return and how to format the result.',
			'required' => array(
				'use',
			),
			'properties' => array(
				'use' => array(
					'type' => 'string',
					'description' => 'Name of the view (defined in \'make\') to return as the result.',
				),
				'limit' => array(
					'type' => 'integer',
					'description' => 'Maximum number of rows to return. Default: 1000, Maximum: 50000.',
					'minimum' => 1,
					'maximum' => 50000,
					'default' => 1000,
				),
				'count_only' => array(
					'type' => 'boolean',
					'description' => 'If true, return only the count of rows instead of the actual data. Default: false.',
					'default' => false,
				),
			),
			'additionalProperties' => false,
			'errors' => array(
				array(
					'code' => 'E_UNKNOWN_VIEW',
					'message' => 'Result.use does not match any defined view in make.',
				),
			),
		),
	),
	'features' => array(
		'filter' => array(
			'enabled' => true,
			'since' => '2025-10-20',
		),
		'join' => array(
			'enabled' => true,
			'since' => '2025-10-20',
		),
		'calc' => array(
			'enabled' => true,
			'since' => '2025-10-20',
		),
		'view_chaining' => array(
			'enabled' => true,
			'since' => '2025-10-20',
		),
		'sort' => array(
			'enabled' => true,
			'since' => '2025-10-20',
		),
		'allpv_prev_next_page' => array(
			'enabled' => true,
			'since' => '2026-04-17',
		),
		'sample' => array(
			'enabled' => false,
		),
		'include_count' => array(
			'enabled' => false,
		),
		'return_file' => array(
			'enabled' => false,
		),
		'return_csv' => array(
			'enabled' => false,
		),
		'return_parquet' => array(
			'enabled' => false,
		),
	),
	'fixed_material_names' => array(
		'allpv',
		'gsc',
		'ga4_age_gender',
		'ga4_country',
		'ga4_region',
		'click_event',
		'datalayer_event',
		'page_version',
	),
);
